[package]
name = "vigia"
version = "0.27.0"
edition = "2021"

[lib]
name = "vigia"
path = "src/lib.rs"

[[bin]]
name = "vigia"
path = "src/main.rs"

[[bin]]
name = "selfplay"
path = "src/bin/selfplay.rs"

[[bin]]
name = "banco"
path = "src/bin/banco/main.rs"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
